github:
  environments:
    release:
      required_reviewers:
        - id: jdaugherty
          type: User
        - id: matrei
          type: User
        - id: jamesfredley
          type: User
        - id: sbglasius
          type: User
      wait_timer: 0
    docs:
      required_reviewers:
        - id: jdaugherty
          type: User
        - id: matrei
          type: User
        - id: jamesfredley
          type: User
        - id: sbglasius
          type: User
      wait_timer: 0
    close:
      required_reviewers:
        - id: jdaugherty
          type: User
        - id: matrei
          type: User
        - id: jamesfredley
          type: User
        - id: sbglasius
          type: User
      wait_timer: 0
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
