projectVersion=5.0.0-SNAPSHOT

# Grails
grailsVersion=7.0.0-M1
grailsGradlePluginVersion=7.0.0-M3
assetPipelineGradleVersion=5.0.8

# Project specific
commonsPool2Version=2.12.0
gormVersion=9.0.0-SNAPSHOT
gsonVersion=2.11.0
jredisVersion=5.2.0

# Example specific
xmlBindApiVersion=4.0.2

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
