name: "Java CI"
on:
  push:
    branches:
      - '[3-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[3-9]+.[0-9]+.x'
  workflow_dispatch:
permissions:
  packages: read
jobs:
  build:
    name: "Build (Redis ${{ matrix.redis-version }})"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        redis-version: [6, 7]
    services:
        redis:
            image: redis:${{ matrix.redis-version }}
            ports:
              - 6379:6379
            options: >-
              --health-cmd "redis-cli ping"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🏃‍♂️ Run Build"
        id: build
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        run: ./gradlew build --continue
  publish_snapshot:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "📤 Publish Snapshot Artifacts"
        id: publish
        env:
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GRAILS_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW }}
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
        run: ./gradlew --no-build-cache publish
      - name: "🔨 Generate Snapshot Documentation"
        run: ./gradlew :grails-redis:groovydoc
      - name: "🚀 Publish to Github Pages"
        uses: apache/grails-github-actions/deploy-github-pages@asf
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_RELEASE: 'false'
          SOURCE_FOLDER: plugin/build/docs
